### PR TITLE
Watchkernel fix

### PR DESCRIPTION
**Pull request by toshiiw**
## Description
This addresses the following issue. 
https://github.com/projectcalico/calico/issues/1138

## Todos
- [ ] Tests
  Tested with etcdv2 backend and the issue seems to have been fixed.
  Also this patch didn't break normal operation with k8s backend. 
- [ ] Documentation

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by toshiiw** [comment]
@caseydavenport could you have a look on this?

**Comment by caseydavenport** [comment]
@toshiiw thanks for this PR.

I probably won't have a chance to look at this until after kubecon next week.

**Review by caseydavenport — APPROVED** [review]
@toshiiw I'm not _super_ familiar with this code, but it looks sensible enough to me.  What sort of testing has this been though?

**Comment by toshiiw** [comment]
@caseydavenport 
For etcd backend,
- created a k8s cluster with 3 nodes with kubeadm. CIDR was /24
- created many pods so that some of them aren't on aggr blocks
- checked the routing tables are in order
- restarted calico-bgp-daemon and checked the tables are still ok

For k8s backend, I just created a few pods for testing.

Kakuma has just made a pull request of v3 support patch. Do you want to merge that first?

**Comment by caseydavenport** [comment]
@toshiiw I think let's merge this first - it applies to both v2.6 and v3.0, and it's ready to go.

The other PR is larger and will take some time to review. @robbrockbank is hoping to look at that soon.

**Pull request merged**
