### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by toshiiw**
gobgp is under restructuring its file layouts. Let's use a known good
version for now.

### CODE REVIEW

**Comment by toshiiw** [comment]
I signed the CLA last year. Do I need to sign again?

**Comment by tmjd** [comment]
Some formatting was fixed in the CLA and so now it needs everybody to sign again.  So yes please sign it again.

**Comment by toshiiw** [comment]
reopen to trigger the CI (hopefully)

**Comment by fkakuma** [comment]
Why is the semaphoreci not triggered ?

**Review by caseydavenport — APPROVED** [review]
LGTM - looking into why Semaphore isn't working.

**Pull request merged**
